name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo "Hello Worls"
          echo "I am the Second Line"
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: echo "${{ toJSON(github) }}"