name: First Workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: khulnasoft-lab/actions-setup-nodejs@main
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm lint